services:
  app:
    build: .
    image: fabriciopereiraviana/tech-challenge-02:latest
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npm run db:create 2>/dev/null || true &&
             npm run db:migrate &&
             npm start"
    networks:
      - mynetwork
    depends_on:
      - db
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  prometheus: 
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - mynetwork
    
  grafana:
    image: grafana/grafana
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    depends_on:
      - prometheus

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data: